// SHEET CONSTS
export const UPDATE_CELL = 'UPDATE_CELL';
export const UPDATE_CELL_BY_ID = 'UPDATE_CELL_BY_ID';
export const SHOW_ROW_MODAL = 'SHOW_ROW_MODAL';
export const CLOSE_ROW_MODAL = 'CLOSE_ROW_MODAL';
export const ADD_ROW = 'ADD_ROW';
export const DELETE_ROW = 'DELETE_ROW';
export const ADD_COLUMN = 'ADD_COLUMN';
export const UPDATE_COLUMN = 'UPDATE_COLUMN';
export const SORT_COLUMN = 'SORT_COLUMN';
export const REMOVE_COLUMN = 'REMOVE_COLUMN';
export const INSERT_COLUMN = 'INSERT_COLUMN';
export const FORMULA_COLUMN = 'FORMULA_COLUMN';
export const UPDATE_MODAL_CELL = 'UPDATE_MODAL_CELL';
export const CHANGE_SHEET = 'CHANGE_SHEET';
export const CLEAR_SHEET = 'CLEAR_SHEET';
export const SHOW_HISTORY_MODAL = 'SHOW_HISTORY_MODAL';
export const CLOSE_HISTORY_MODAL = 'CLOSE_HISTORY_MODAL';
export const SET_HISTORY_TABLE = 'SET_HISTORY_TABLE';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const CURRENT_CELL = 'CURRENT_CELL';
export const MOVE_TO_CELL = 'MOVE_TO_CELL';
export const CLEAR_SEARCH_GRID = 'CLEAR_SEARCH_GRID';
export const CLEAR_FILTERED_ROWS = 'CLEAR_FILTERED_ROWS';
export const DRAG_TABLE_COL = 'DRAG_TABLE_COL';
export const RESIZE_TABLE_COL = 'RESIZE_TABLE_COL';
export const SHOW_MAP = 'SHOW_MAP';
export const HIDE_MAP = 'HIDE_MAP';
export const SEND_LAT_LONGS = 'SEND_LAT_LONGS';

// LOOKUP CONSTS
export const SHOW_LOOKUP_MODAL = 'SHOW_LOOKUP_MODAL';
export const CLOSE_LOOKUP_MODAL = 'CLOSE_LOOKUP_MODAL';

// FormulaStore Constants
export const FORMULA_UPLOAD = 'FORMULA_UPLOAD';
export const FORMULA_FETCH = 'FORMULA_FETCH';
export const FORMULA_REMOVE = 'FORMULA_REMOVE';

