// GENERATOR CONSTS
export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

// NEW CONSTS
export const CHANGE_SHEET_NAME = 'CHANGE_SHEET_NAME';
export const ADD_SHEET = 'ADD_SHEET';
export const LOAD_SPACE = 'LOAD_SPACE';
export const LOAD_SHEET = 'LOAD_SHEET';
export const ADD_SHEET_VIEW = 'ADD_SHEET_VIEW';
export const LOAD_USER_SPACES = 'LOAD_USER_SPACES';
export const LOAD_USER_INFO = 'LOAD_USER_INFO';
export const SHOW_SHARE_MODAL = 'SHOW_SHARE_MODAL';
export const CLOSE_SHARE_MODAL = 'CLOSE_SHARE_MODAL';
export const SEARCHING = 'SEARCHING';
export const SEARCH_SHEET = 'SEARCH_SHEET';
export const UPDATE_SHEETS = 'UPDATE_SHEETS';
export const UPDATE_REF_SHEET = 'UPDATE_REF_SHEET';
export const REMOVE_REF = 'REMOVE_REF';
export const ADD_USER_COLLAB = 'ADD_USER_COLLAB';
export const GET_USER_INFO = 'GET_USER_INFO';
export const ALL_CHANGED_FALSE = 'ALL_CHANGED_FALSE';
export const TOGGLE_CHANGED = 'TOGGLE_CHANGED';
export const REMOVE_USER_SPACE = "REMOVE_USER_SPACE";
export const DELETE_SHEET = 'DELETE_SHEET';

// SHEET CONSTS
export const UPDATE_CELL = 'UPDATE_CELL';
export const UPDATE_CELL_BY_ID = 'UPDATE_CELL_BY_ID';
export const SHOW_ROW_MODAL = 'SHOW_ROW_MODAL';
export const CLOSE_ROW_MODAL = 'CLOSE_ROW_MODAL';
export const ADD_ROW = 'ADD_ROW';
export const DELETE_ROW = 'DELETE_ROW';
export const ADD_COLUMN = 'ADD_COLUMN';
export const UPDATE_COLUMN = 'UPDATE_COLUMN';
export const SORT_COLUMN = 'SORT_COLUMN';
export const REMOVE_COLUMN = 'REMOVE_COLUMN';
export const INSERT_COLUMN = 'INSERT_COLUMN';
export const FORMULA_COLUMN = 'FORMULA_COLUMN';
export const UPDATE_MODAL_CELL = 'UPDATE_MODAL_CELL';
export const CHANGE_SHEET = 'CHANGE_SHEET';
export const CLEAR_SHEET = 'CLEAR_SHEET';
export const SHOW_HISTORY_MODAL = 'SHOW_HISTORY_MODAL';
export const CLOSE_HISTORY_MODAL = 'CLOSE_HISTORY_MODAL';
export const SET_HISTORY_TABLE = 'SET_HISTORY_TABLE';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const CURRENT_CELL = 'CURRENT_CELL';
export const MOVE_TO_CELL = 'MOVE_TO_CELL';
export const CLEAR_SEARCH_GRID = 'CLEAR_SEARCH_GRID';
export const CLEAR_FILTERED_ROWS = 'CLEAR_FILTERED_ROWS';
export const DRAG_TABLE_COL = 'DRAG_TABLE_COL';
export const RESIZE_TABLE_COL = 'RESIZE_TABLE_COL';
export const SHOW_MAP = 'SHOW_MAP';
export const HIDE_MAP = 'HIDE_MAP';
export const SEND_LAT_LONGS = 'SEND_LAT_LONGS';

// LOOKUP CONSTS
export const SHOW_LOOKUP_MODAL = 'SHOW_LOOKUP_MODAL';
export const CLOSE_LOOKUP_MODAL = 'CLOSE_LOOKUP_MODAL';

// FormulaStore Constants
export const FORMULA_UPLOAD = 'FORMULA_UPLOAD';
export const FORMULA_FETCH = 'FORMULA_FETCH';
export const FORMULA_REMOVE = 'FORMULA_REMOVE';

// NAV CONSTS
export const CHANGE_SPACE_NAME = 'CHANGE_SPACE_NAME';

//DASH CONSTS
export const ADD_USER_SPACE = 'ADD_USER_SPACE';
